### ISSUE TITLE
Lesson button should cursor: pointer; set

### ISSUE THREAD

**Issue by benorgan** [redacademy/blockwise-winter-2019#5]
The lesson button (on https://blockwise.van.cp.academy.red/lesson/) should have cursor: pointer set so users realise the lesson is clickable. You can either do this in CSS or change the `<div>` to be an `<a>`

**Comment by benorgan** [comment]
You have the same issue on this page https://blockwise.van.cp.academy.red/membership/

**Comment by athistlethwaite** [comment]
Fixed for lesson page
