### ISSUE TITLE
Ensure all files are lowercase without spaces or special characters

### ISSUE THREAD

**Issue by benorgan** [redacademy/blockwise-winter-2019#6]
Your images have uppercase letters in, please change to be lowercase (using `git mv` to avoid Git issues): 

https://github.com/redacademy/blockwise-winter-2019/blob/e7cf26ac6fed981a4ed68f20b38af8f8fd779ee9/themes/blockwise-theme/footer.php#L15-L18

**Comment by athistlethwaite** [comment]
Fixed
